# Generated by Django 4.2.5 on 2023-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20231113_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transactions',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
