# Generated by Django 4.2.5 on 2023-11-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_bank_transactions_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transactions',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
