# Generated by Django 4.2.5 on 2023-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_bank_transactions_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_account',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='intrest',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='paid',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan_account',
            name='processing',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
