# Generated by Django 4.2.5 on 2023-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_alter_loan_account_desc_alter_loan_account_intrest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_transaction',
            name='loan_intrest',
            field=models.TextField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
